const ResponseMessages = {
    EMAIL_ALREADY_EXIST: "Email already exists",
    USER_NOT_FOUND: "User not found",
    INVALID_DATA: "Invalid data",
    INTERNAL_SERVER_ERROR_MSG: "Internal server error",
    PASSWORD_DONT_MATCH: "Credentials of the user does'nt match",
    UNABLE_LOGIN: "Unable to login",
    UNABLE_TO_CREATE_USER: "Unable to create user",
    UNABLE_Add_GAME: "Unable to add game",
    UNABLE_FETCH_GAME: "Unable to fetch game",
    UNABLE_Add_GAME_DATA: "Unable to add game data",
    UNABLE_FETCH_GAME_DATA: "Unable to fetch game data",
    UNABLE_TO_ADD_LEARNING_PATH: "Unable to add Game Learning Path",
    LEARNINGPATH_ALREADY_EXIST: "Learning path already exists",
    LEARNINGPATH_NOT_FOUND: "No learning path found with given id",
    UNABLE_TO_UPDATE_LEARNING_PATH: "Unable to update learning path",
    UNABLE_Add_CHILD: "Unable to add child data",
    UNABLE_Add_CHILD_TO_GRADE: "Unable to add child to this grade",
    INVALID_UPDATES: "Invalid updates",
    NO_CHILD: "No child found with this id",
    UNABLE_UPDATE_CHILD: "Unable to update child",
    UNABLE_TO_FIND_CHILD: "Unable to find child",
    UNABLE_TO_UPGRADE_CHILD: "Unable to UPGRADE child",
    UNABLE_LOGOUT: "Unable to logout",
    LOGOUT_SUCCESS: "Logged out successfully",
    NO_DATA_FOUND: "No data found",
    GAME_DATA_DUPLICATION: "Unable to add game-data due to duplication",
    UNABLE_FETCH_LEARNINGPATH_DATA: "Unable to fetch learning path data",
    MILESTONE_NOT_FOUND: "Unable to find milestone",
    UNABLE_TO_UPDATE_MILESTONE: "Unable to update milestone",
    UNABLE_TO_ADD_MILESTONE: "Unable to add milestone"
}

module.exports = ResponseMessages;